version: "3"
services:
  mage:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env_dev
    build:
      context: .
      dockerfile: Dockerfile.Mage
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - ./etl/:/home/src/
    restart: on-failure:5

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3456:3000
    environment:
      - .env_dev
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: datawarehouse
      # MB_DB_PORT: 5432
      # MB_DB_USER: metabase_admin
      # MB_DB_PASS: meTaBaSeAdmin
      # MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - .env_dev
      # POSTGRES_USER: metabase_admin
      # POSTGRES_DB: datawarehouse
      # POSTGRES_PASSWORD: meTaBaSeAdmin
