apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: analytics-project

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: longbuivan95.external@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-ingress
  namespace: analytics-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - datapods.io
    secretName: letsencrypt-prod
  ingressClassName: nginx
  rules:
  - host: viz.datapods.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
  - host: etl.datapods.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mage
            port:
              number: 80